### PR TITLE
Update install instructions in readme.

### LINKED ISSUE #27: Can't retrieve mixtool using go get
Hi,
i try to retrieve mixtool, i've got this error : 

```
$ go version
go version go1.15.3 linux/amd64
$ go get -u github.com/monitoring-mixins/mixtool/cmd/mixtool
# github.com/monitoring-mixins/mixtool/cmd/mixtool
golang/src/github.com/monitoring-mixins/mixtool/cmd/mixtool/generate.go:32:22: cannot use cli.StringSliceFlag literal (type cli.StringSliceFlag) as type cli.Flag in slice literal:
        cli.StringSliceFlag does not implement cli.Flag (Apply method has pointer receiver)
golang/src/github.com/monitoring-mixins/mixtool/cmd/mixtool/generate.go:35:3: undefined: cli.BoolTFlag
golang/src/github.com/monitoring-mixins/mixtool/cmd/mixtool/generate.go:44:15: cannot use cli.Command literal (type cli.Command) as type *cli.Command in slice literal
golang/src/github.com/monitoring-mixins/mixtool/cmd/mixtool/generate.go:47:18: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in append:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
golang/src/github.com/monitoring-mixins/mixtool/cmd/mixtool/generate.go:55:15: cannot use cli.Command literal (type cli.Command) as type *cli.Command in slice literal
golang/src/github.com/monitoring-mixins/mixtool/cmd/mixtool/generate.go:58:18: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in append:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
golang/src/github.com/monitoring-mixins/mixtool/cmd/mixtool/generate.go:66:15: cannot use cli.Command literal (type cli.Command) as type *cli.Command in slice literal
golang/src/github.com/monitoring-mixins/mixtool/cmd/mixtool/generate.go:69:18: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in append:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
golang/src/github.com/monitoring-mixins/mixtool/cmd/mixtool/generate.go:77:15: cannot use cli.Command literal (type cli.Command) as type *cli.Command in slice literal
golang/src/github.com/monitoring-mixins/mixtool/cmd/mixtool/generate.go:80:18: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in append:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
golang/src/github.com/monitoring-mixins/mixtool/cmd/mixtool/generate.go:77:15: too many errors
```

Any idea ? 
what do you think about provides binaries from releases ?

### PR DESCRIPTION
**Pull request by tomwilkie**
Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

Fixes #27

### CODE REVIEW

**Comment by tomwilkie** [comment]
(test and lint failures fixed in #33)

**Review by brancz — APPROVED** [review]
